name: Kris Hartrum
author: Kris Hartrum
keywords:
description: The website of writer Kris Hartrum.
markdown: redcarpet
permalink: /:categories/:title
paginate: 7
paginate_path: /blog/:num/
exclude:
  - config.rb
  - .gitignore
  - .sass-cache
  - scss
