name: Kris Hartrum
author: Kris Hartrum
keywords:
description: The website of writer Kris Hartrum.
markdown: redcarpet
permalink: /:categories/:title
paginate: 7
paginate_path: /blog/:num/
prose:
  media: "media"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
