name: Kris Hartrum
author: Kris Hartrum
keywords:
description: The website of writer Kris Hartrum.
markdown: redcarpet
permalink: /blog/:year/:month/:title
prose:
  media: "resources"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "Photo URL"
          value: "/resources/"
