name: Kris Hartrum
author: Kris Hartrum
keywords:
description: The website of writer Kris Hartrum.
markdown: redcarpet
permalink: /:categories/:title
paginate: 7
paginate_path: /blog/:num/
exclude:
  - config.rb
  - .gitignore
  - .sass-cache
  - scss
prose:
  media: "media"
  rooturl: "_posts"
  siteurl: "https://www.krishartrum.com/"
  metadata:
    _posts/about:
      - name: "categories"
        field:
          element: "hidden"
          value: 
            - "about"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "official"
        field: 
          element: "checkbox"
          label: "Official About Info"
          value: "false"
    _posts/blog:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "categories"
        field:
          element: "hidden"
          value: 
            - "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
    _posts/contact:
      - name: "categories"
        field:
          element: "hidden"
          value: 
            - "contact"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: "Contact Kris"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "official"
        field: 
          element: "checkbox"
          label: "Official Contact Info"
          value: "false"
    _posts/work:
      - name: "categories"
        field:
          element: "hidden"
          value: 
            - "work"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "link"
        field:
          element: "text"
          label: "Link to Work"
          value: "http://"
      - name: "domain"
        field:
          element: "text"
          label: "domain"
          value: ""
          placeholder: "If the article is no longer online use: \'example.com\'"

