name: Kris Hartrum
author: Kris Hartrum
keywords:
description: The website of writer Kris Hartrum.
markdown: redcarpet
permalink: /:categories/:title
paginate: 7
paginate_path: /blog/:num/
exclude:
  - config.rb
  - .gitignore
  - .sass-cache
  - scss
prose:
  media: "media"
  rooturl: "_posts"
  siteurl: "https://www.krishartrum.com/"
  metadata:
    _posts/about:
      - name: "categories"
        field:
          element: "hidden"
          value: 
            - "about"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "official"
        field: 
          element: "checkbox"
          label: "Official About Info"
          value: "false"
    _posts/blog:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "categories"
        field:
          element: "hidden"
          value: 
            - "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
    _posts/contact:
      - name: "categories"
        field:
          element: "hidden"
          value: 
            - "contact"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: "Contact Kris"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "official"
        field: 
          element: "checkbox"
          label: "Official Contact Info"
          value: "false"
    _posts/work:
      - name: "categories"
        field:
          element: "hidden"
          value: 
            - "work"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "link"
        field:
          element: "text"
          label: "Link to Work"
          value: "http://"
      - name: "domain"
        field:
          element: "text"
          label: "Optional Domain (example.com)"
          value: ""
      - name: "type"
        field:
          element: "select"
          label: "Writing or Project"
          options:
            - name: "Writing"
              value: "writing"
            - name: "Project"
              value: "project"
      - name: "genre"
        field:
          element: "text"
          label: "Genre"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "work"
      - name: "selected"
        field: 
          element: "checkbox"
          label: "Selected"
          value: "false"

